### ISSUE TITLE
sendActions not called if isContinuous = false

### ISSUE THREAD

**Issue by digitalism** [daprice/iOS-Tactile-Slider#6]
I think there is the following problem:

If the slider is set to `isContinuous = false` and the user drags to the maximum or minimum, `sendActions(for: .valueChanged)` is not fired.

Reason is, in `didPan(sender: UIPanGestureRecognizer)`, you stop handing the pan if `value == minimum && valueChange < 0` or `value == maximum && valueChange > 0`.

Action should still be sent once even for minimum or maximum value.
Otherwise it is impossible to detect if slider is set to minimum/maximum.

**Comment by daprice** [comment]
Fix released in 2.0.1. Thanks for diagnosing the source of this
