### ISSUE TITLE
The iOS Simulator deployment target is set to 8.0, but the range of supported deployment target versions is 9.0 to 14

### ISSUE THREAD

**Issue by kikolobo** [daprice/iOS-Tactile-Slider#7]
I think this warning does not allow to render the IBInspectable requirements.

'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99.

**Comment by daprice** [comment]
Fixed in release 3.0.0 which requires iOS 9.
