### ISSUE TITLE
On change function

### ISSUE THREAD

**Issue by novacom34** [daprice/iOS-Tactile-Slider#8]
Hi. Thanks for framework. How can I get onChangeValue function?

**Comment by daprice** [comment]
As a subclass of UIControl, this uses the target-action pattern. Call `TactileSlider.addTarget(_:action:for:)` to register for `valueChanged` events. See the [UIControl documentation](https://developer.apple.com/documentation/uikit/uicontrol#1658488) for more information about how to use this pattern.
